### ISSUE TITLE
compiler.jar appears dangerous

### ISSUE THREAD

**Issue by csuhta** [twerno/gw2BBCode#4]
`compile_debug.bat` and `compile_dist.bat` both invoke Java to run `compiler.jar` to produce minified code. 

While it's possible to download and unpack the `jar` to inspect the contents, it contains `.class` bytecode that is not easily auditable. To new users of the project this can appear malicious, as if you are trying to trick people into running a Java jar on their system.

The project should include a more transparent tool for minifying the JS like a [Gruntfile that invokes UglifyJS](https://github.com/jquery/jquery/blob/master/Gruntfile.js). Alternatively: none at all, since the stated primary means of including the minified source seems to be [from your server](http://gw2bbcode.pl). Users who want to deploy the JS on their server will usually use their own minifying strategy anyway.

**Comment by twerno** [comment]
You may be right about that one as well.
There are no info at all that `compiler.jar` is in fact the [Closure-compiler](https://developers.google.com/closure/) - an open source JavaScript optimization tool.

I added a `README` to the compiler dir and removed `compiler.jar` from the project.
