### ISSUE TITLE
Flag or Remove Google Analytics Tracking

### ISSUE THREAD

**Issue by csuhta** [twerno/gw2BBCode#5]
The project has code to add Google Analytics tracking to every site that includes the script, code is [here](https://github.com/twerno/gw2BBCode/blob/936d30ddc81b255cf55ca8f1401d6707ee50a58e/gw2BBCode_core.js#L14) and [here](https://github.com/twerno/gw2BBCode/blob/936d30ddc81b255cf55ca8f1401d6707ee50a58e/gw2BBCode_core.js#L263-L273).

This could be construed as spyware-like or malicious. It may also violate the site's `Content-Security-Policy`. A note about the GA code should be stated on both the project's `README` and website. More ideally: the code should be removed. 

I am willing to submit a pull request to remove it, but as your project is structured now, that pull request would need to include minified code, and I am not willing to run `compiler.jar`. See issue #4.

**Comment by twerno** [comment]
You're right. GA has been removed.
