### ISSUE TITLE
Macro: Mesmer Torch #4 Shows a Guardian Skill

### ISSUE THREAD

**Issue by jbolda** [twerno/gw2BBCode#6]
[Me:Scepter/torch] gives skill number 4 as [Chains of Light]

It is reproducible on http://gw2bbcode.pl .

**Comment by twerno** [comment]
Fixed.

**Comment by jbolda** [comment]
Can I presume that is was fixed in 7e3910fc7bb9f16e0f9e5c2df4bba3b5a40f49ff? One the the CSS elements was interacting badly with our enjin site and hiding the navigation bar so I just copied the files over and deleted that piece. Long story short, I am going to have to manual make the change myself.
